//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cave_Adventure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cave_Adventure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap andesiteBackground {
            get {
                object obj = ResourceManager.GetObject("andesiteBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1.#1.#1.#1.#1.#1.#1.#1.#1.#1.
        ///  .P .  .  .  .  .  .  .Sl.#1.
        ///#1.#1.#1.#1.#1.#1.#1.#1.#1.#1..
        /// </summary>
        internal static string Arena1 {
            get {
                return ResourceManager.GetString("Arena1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4.#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.
        ///#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.  .  .  .  .#4.#4.#4.#4.#4.
        ///#4.#4.#4.#4.#4.#4.#4.#4.#4.#4.Sl.  .  .  .  .  .#4.#4.#4.#4.
        ///#4.#4.#4.  .  .  .  .#4.#4.  .  .  .  .  .  .  .  .#4.#4.#4.
        ///#4.Wi.  .  .#4.#4.  .#4.Sl.  .  .Sl.Sl.  .  .  .  .  .#4.#4.
        ///#4.  .#4.  .#4.#4.  .#4.  .  .  .  .  .  .  .  .  .  .#4.#4.
        ///#4.  .  .  .#4.#4.  .  .  .Sl.Sl.  .  .  .  .  .  .Mi.  .  .
        ///#4.  .#4.  .#4.#4.  .#4.  .  .  .  .  .  .  .  .  .  .#4.#4.
        ///#4.Wi.  .  .#4.# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arena10 {
            get {
                return ResourceManager.GetString("Arena10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #T.#T.#T.#T.#T.#T.#T.#T.#T.#T.
        ///#T.#T.#T.#T.#T.#T.#T.#T.#T.#T.
        ///#T.#T.#T.#T.#T.#T.#T.#T.#T.#T.
        ///#T.#T.#T.# .# .# .# .# .# .# .
        ///#T.#T.#T.# .  .P .  .  .  .# .
        ///#T.#T.#T.# .# .  .  .# .  .# .
        ///#T.#T.#T.# .  .  .  .  .  .# .
        ///#T.#T.#T.# .  .  .  .  .  .# .
        ///#T.#T.#T.# .Sp.  .Sn.  .  .# .
        ///#T.#T.#T.# .# .# .# .# .# .# ..
        /// </summary>
        internal static string Arena1Debug {
            get {
                return ResourceManager.GetString("Arena1Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1.#1.#1.#1.#1.#1.#1.#1.#1.#1.
        ///#1.P .  .  .  .#1.  .  .  .#1.
        ///#1.#1.#1.#1.  .#1.  .#1.  .#1.
        ///#1.  .Sl.#1.  .#1.Sp.#1.  .#1.
        ///#1.  .#1.#1.  .#1.#1.#1.  .#1.
        ///#1.  .  .  .  .  .  .  .  .#1.
        ///#1.#1.#1.#1.#1.#1.#1.#1.#1.#1..
        /// </summary>
        internal static string Arena2 {
            get {
                return ResourceManager.GetString("Arena2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # .# .# .# .# .#0.#1.#2.#3.#4.
        ///# .  .P .Sp.  .#0.#1.#2.#3.#4.
        ///# .# .  .# .  .#0.#1.#2.#3.#4.
        ///# .  .# .  .  .#0.#1.#2.#3.#4.
        ///  .  .  .  .  .  .  .  .  .  .
        ///#0.#0.  .#1.#1.  .#2.#2.  .# .
        ///#0.#0.  .#1.#1.  .#2.#2.  .# .
        ///  .  .  .  .  .  .  .  .  .# .
        ///#3.#3.  .#4.#4.  .  .  .  .# .
        ///#3.#3.  .#4.#4.  .  .  .  .# ..
        /// </summary>
        internal static string Arena2Debug {
            get {
                return ResourceManager.GetString("Arena2Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1.#1.#1.#1.#1.#1.#1.#2.#1.#2.#1.
        ///#1.  .  .  .  .  .#2.  .Sp.  .#2.
        ///#1.  .  .#1.  .  .#1.  .  .  .#1.
        ///#1.  .  .#1.  .  .  .  .  .  .#2.
        ///#1.  .  .#1.  .  .#1.  .  .  .#1.
        ///#1.  .  .#1.  .  .#2.  .  .  .#2.
        ///#1.  .  .#1.  .  .#1.  .Sp.  .#1.
        ///#1.  .Sp.#1.  .  .#2.  .  .  .#2.
        ///#1.  .  .#1.Sl.  .#1.#2.#1.#2.#1.
        ///#1.#1.#1.#1.  .  .#1.#1.#1.#1.#1.
        ///#1.P .  .Sl.  .  .  .  .Sl.  .#1.
        ///#1.#1.#1.#1.#1.#1.#1.#1.#1.#1.#1..
        /// </summary>
        internal static string Arena3 {
            get {
                return ResourceManager.GetString("Arena3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # .# .# .# .# .# .# .# .# .# .# .
        ///# ..# .  .  .  .  .  .  .  .  .# .
        ///# . .# .  .# .  .  .  .  .  .  .# .
        ///# .  .# .  .# .  .  .  . .  .
        ///# .  .  .  .# .# .# .# .# .  .# .# .
        ///# .# .# .  .  .  .  .  .  .  .  .# .
        ///# .  .# .  .  .  .P .  .  .  .  .# .
        ///# .  .  .  .# .  .# .# .# .# .# .# .
        ///# .  .  .  .# .Go.Sp.  .  .  .  .# .
        ///# .  .  .  .# .  .  .  .  .  .  .# .
        ///# .  .  .  .# .Sp.  .  .  .  .  .# .
        ///# .# .# .# .# .# .# .# .# .# .# .# ..
        /// </summary>
        internal static string Arena3Debug {
            get {
                return ResourceManager.GetString("Arena3Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1.#2.#1.#2.#1.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.P .  .  .  .  .  .  .  .Sp.#2.#2.#2.#2.#2.
        ///#1.#2.#1.#2.#1.  .#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.#2.#2.#2.#2.  .#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.#2.#2.#2.#2.  .#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.#2.#2.#2.#2.  .#2.#2.#2.  .  .  .  .  .#2.
        ///#2.#2.#2.#2.#2.Sn.#2.#2.#2.  .#2.#2.#2.  .#2.
        ///#2.#2.#2.#2.#2.  .#2.#2.#2.  .#2.#2.#2.  .#2.
        ///#2.  .  .Sp.#2.  .#2.  .  .Sp.#2.#2.#2.  .#2.
        ///#2.Sl.  .  .  .  .#2.Sl.  .  .#2.#2.#2.  .#2.
        ///#2.  .  .Sl.  .  .  .  .  .Sl.#2.#2.#2.Sn. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arena4 {
            get {
                return ResourceManager.GetString("Arena4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # .# .# .# .# .# .# .# .# .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .  .  .P .  .  .  .  .  .# .
        ///# .  .  .Sn.  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .# .# .# .# .# .# .# .# .# ..
        /// </summary>
        internal static string Arena4Debug {
            get {
                return ResourceManager.GetString("Arena4Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.  .  .  .Sn.  .  .  .  .  .  .  .#2.#2.
        ///#2.  .#2.#2.#2.#2.  .  .#2.#2.#2.  .#2.#2.
        ///#2.  .#2.#2.#2.#2.#2.  .Go.#2.#2.  .#2.#2.
        ///#2.  .#2.  .Sp.#2.#2.#2.#2.#2.#2.Go.#2.#2.
        ///#2.  .  .  .  .#2.#2.#2.#2.#2.  .  .Sp.#2.
        ///#2.Sp.#2.  .Sn.#2.#2.#2.#2.#2.  .#2.#2.#2.
        ///#2.  .#2.#2.#2.#2.#2.#2.#2.#2.  .  .#2.#2.
        ///#2.  .#2.#2.#2.#2.#2.#2.#2.#2.  .  .  .#2.
        ///#2.  .#2.#2.#2.#2.#2.#2.#2.#2.Sp.  .  .#2.
        ///#2.P .#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.Sn.#2.
        ///#2.#2.#2.#2.#2.#2.#2.#2.#2.# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arena5 {
            get {
                return ResourceManager.GetString("Arena5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # .# .# .# .# .# .# .# .# .# .
        ///# .P .  .Sp.Sp.Sp.Sp.Sp.Sp.# .
        ///# .Sn.Sn.Sn.Sn.Sn.Sn.Sn.Sn.# .
        ///# .Sp.Sp.Sp.Sp.Sp.Sp.Sp.Sp.# .
        ///# .Sn.Sn.Sn.Sn.Sn.Sn.Sn.Sn.# .
        ///# .Sp.Sp.Sp.Sp.Sp.Sp.Sp.Sp.# .
        ///# .Sn.Sn.Sn.Sn.Sn.Sn.Sn.Sn.# .
        ///# .Sp.Sp.Sp.Sp.Sp.Sp.Sp.Sp.# .
        ///# .Sn.Sn.Sn.Sn.Sn.Sn.Sn.Sn.# .
        ///# .# .# .# .# .# .# .# .# .# ..
        /// </summary>
        internal static string Arena5Debug {
            get {
                return ResourceManager.GetString("Arena5Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.Sp.  .  .  .  .#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.#2.#2.Go.#2.  .#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.#2.#2.#2.#2.  .  .  .  .  .  .#2.#2.#2.#2.
        ///#2.#2.#2.#2.#2.  .#2.#2.#2.#2.Sn.  .  .  .#2.
        ///#2.P .  .  .  .  .#2.#2.#2.#2.Sp.#2.#2.  .#2.
        ///#2.#2.#2.#2.#2.  .#2.#2.#2.#2.  .#2.#2.  .#2.
        ///#2.#2.#2.#2.#2.  .  .  .  .  .  .#2.#2.Go.#2.
        ///#2.Go.#2.#2.#2.  .#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.  .  .  .  .Sp.#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arena6 {
            get {
                return ResourceManager.GetString("Arena6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # .# .# .# .# .# .# .# .# .# .# .# .# .# .# .# .# .# .# .# .
        ///# .P .  .  .  .  .  .  .  .  .  .  .# .# .# .# .# .# .# .# .
        ///# .  .  .  .  .  .  .  .  .  .  .  .# .# .# .# .# .# .# .# .
        ///# .  .  .  .  .  .  .  .  .  .  .  .# .# .# .# .# .# .# .# .
        ///# .  .  .  .  .  .  .  .  .  .  .  .# .# .# .# .# .# .# .# .
        ///# .  .  .  .  .Mi.  .  .  .  .  .  .# .# .# .# .# .# .# .# .
        ///# .  .  .  .  .  .  .  .  .  .  .  .# .# .# .# .# .# .# .# .
        ///# .  .  .  .  .  .  .  .  .  .  .  .# .# .# .# .# .# .# .# .
        ///# .  .  .  .  .  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arena6Debug {
            get {
                return ResourceManager.GetString("Arena6Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.P .  .#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.#2.
        ///#2.#2.  .  .#2.#2.#2.  .  .  .Gh.  .#2.#2.#2.
        ///#2.#2.#2.  .  .#2.#2.  .#2.#2.#2.  .#2.#2.#2.
        ///#2.#2.#2.#2.  .  .#2.  .#3.#2.  .  .  .Sn.#2.
        ///#2.#2.#2.#2.#2.  .Sn.  .#2.#3.  .  .  .  .#2.
        ///#2.#2.#2.#2.#2.#2.  .  .  .#2.#3.Sn.  .#2.#2.
        ///#2.Sn.  .#2.#2.#2.  .#3.  .  .#2.#3.#2.#3.#2.
        ///#2.  .  .  .#2.#2.  .#2.#3.  .  .  .  .Sn.#3.
        ///#2.  .  .  .Gh.  .  .#3.#2.#2.  .  .  .#3.#2.
        ///#2.#2.Go.#2.#2.#2.#2.#2.#3.#2.#3.Go.  .Gh. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arena7 {
            get {
                return ResourceManager.GetString("Arena7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # .# .# .# .# .# .# .# .# .# .
        ///# .P .# .  .  .  .  .  .  .# .
        ///# .  .# .# .  .  .  .  .  .# .
        ///# .Mi.  .# .  .  .  .  .  .# .
        ///# .# .# .# .  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .  .  .  .  .  .  .  .  .# .
        ///# .# .# .# .# .# .# .# .# .# ..
        /// </summary>
        internal static string Arena7Debug {
            get {
                return ResourceManager.GetString("Arena7Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.
        ///#3.  .Go.#3.#3.  .  .  .  .  .  .  .  .  .Gh.  .#3.
        ///#3.  .  .#3.#3.  .#3.#3.#3.#3.#3.#3.#3.#3.#3.  .#3.
        ///#3.  .#3.#3.#3.  .#3.#3.#3.#3.#3.Go.#3.Go.#3.  .#3.
        ///#3.Go.  .  .#3.  .#3.#3.#3.#3.#3.  .  .  .  .  .#3.
        ///#3.#3.#2.  .#3.  .#3.#3.#3.#3.#3.#3.  .Go.  .  .#3.
        ///#3.#3.#3.  .  .  .#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.
        ///#3.#3.#2.  .Gh.  .  .  .#3.#3.#3.#3.#3.#3.#3.#3.#3.
        ///#3.#2.#3.  .  .#2.#3.  .#3.#3.#3.#3.  .  .#3.#3.#3.
        ///#2.#3.  .  .  .#3.#3.  .  .  .Gh.#3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arena8 {
            get {
                return ResourceManager.GetString("Arena8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.#3.
        ///#3.P .  .  .  .  .  .  .  .  .  .  .  .  .  .  .#3.#3.Gh.#3.
        ///#3.  .#3.  .#3.#3.#3.#3.#3.#3.#3.Gh.#3.#3.#3.  .#3.#3.  .#3.
        ///#3.  .#3.  .#3.#3.#3.#3.#3.#3.  .  .  .#3.#3.  .  .  .  .#3.
        ///#3.  .#3.#3.#3.#3.#3.#3.#3.#3.Wi.#3.Go.#3.#3.#3.  .  .#3.#3.
        ///#3.  .#3.  .Go.  .  .#3.#3.#3.#3.#3.#3.#3.#3.#3.  .  .#3.#3.
        ///#3.  .#3.  .#3.#3.  .#3.#3.Go.  .  .Gh.#3.#3.#3.Wi.#3.#3.#3.
        ///#3.  .  .  .#3.#3.  .#3.#3.#3.  .  .#3.#3.#3.#3.  .  .#4.#3.
        ///#3.  .#3.#3.#3.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arena9 {
            get {
                return ResourceManager.GetString("Arena9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Холод и сырость. Вот что вас окружает. «Где я?» - бегает мысль в вашей голове.
        ///      
        ///Вы очнулись в непонятном подземелье, мало что помня о себе. Единственным источником света является огромная расщелина в потолке, через которую, в холодную комнату, проникают теплые лучи солнца, но она находиться слишком высоко, что бы можно было выбраться через неё.
        ///«И почему люди не могут летать?» - с этой мыслю вы осматриваете пространство вокруг себя и обнаруживаете на полу старый, но добротный меч и факел с огнивом. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BeginningOfStory {
            get {
                return ResourceManager.GetString("BeginningOfStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cobra {
            get {
                object obj = ResourceManager.GetObject("Cobra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dioriteBackground {
            get {
                object obj = ResourceManager.GetObject("dioriteBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dwarf {
            get {
                object obj = ResourceManager.GetObject("Dwarf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap endBackground {
            get {
                object obj = ResourceManager.GetObject("endBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минотавр повержен. Вы проходите в коридор, который он закрывал. 
        ///Этот проход явно длиннее всех остальных. Вы готовитесь к худшему. Однако, неожиданно для себя, вы встречаете лестницу. И она ведёт вверх! Неужели это выход?
        ///      
        ///Спустя длительное время вы замечаете, что становиться светлее. Откуда-то спереди, с того поворота льётся свет!
        ///      
        ///И вот вы наконец-то на поверхности земли! Свежий воздух пьянит вашу голову. И вам не вериться, что вы смогли выбраться из того кошмара. Однако это так. Вы на св [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EndOfStory {
            get {
                return ResourceManager.GetString("EndOfStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floorStone1 {
            get {
                object obj = ResourceManager.GetObject("floorStone1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floorStone2 {
            get {
                object obj = ResourceManager.GetObject("floorStone2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floorStoneBroken {
            get {
                object obj = ResourceManager.GetObject("floorStoneBroken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ghoul {
            get {
                object obj = ResourceManager.GetObject("Ghoul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gladiator {
            get {
                object obj = ResourceManager.GetObject("Gladiator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grass1 {
            get {
                object obj = ResourceManager.GetObject("grass1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grass2 {
            get {
                object obj = ResourceManager.GetObject("grass2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grass3 {
            get {
                object obj = ResourceManager.GetObject("grass3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grass4 {
            get {
                object obj = ResourceManager.GetObject("grass4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grass5 {
            get {
                object obj = ResourceManager.GetObject("grass5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gravelBackground {
            get {
                object obj = ResourceManager.GetObject("gravelBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ironBarsBackground {
            get {
                object obj = ResourceManager.GetObject("ironBarsBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mazePicBackground1 {
            get {
                object obj = ResourceManager.GetObject("mazePicBackground1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mazePicBackground2 {
            get {
                object obj = ResourceManager.GetObject("mazePicBackground2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mazePicMainMenu {
            get {
                object obj = ResourceManager.GetObject("mazePicMainMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mini_Golem {
            get {
                object obj = ResourceManager.GetObject("Mini_Golem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minotaur {
            get {
                object obj = ResourceManager.GetObject("Minotaur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap netherBackground {
            get {
                object obj = ResourceManager.GetObject("netherBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noTexture {
            get {
                object obj = ResourceManager.GetObject("noTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap obsidianBackground {
            get {
                object obj = ResourceManager.GetObject("obsidianBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap polishedAndesiteBackground {
            get {
                object obj = ResourceManager.GetObject("polishedAndesiteBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap polishedBasaltBackground {
            get {
                object obj = ResourceManager.GetObject("polishedBasaltBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap polishedBlackstoneBackground {
            get {
                object obj = ResourceManager.GetObject("polishedBlackstoneBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap polishedDioriteBackground {
            get {
                object obj = ResourceManager.GetObject("polishedDioriteBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap polishedGraniteBackground {
            get {
                object obj = ResourceManager.GetObject("polishedGraniteBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quartzBackground {
            get {
                object obj = ResourceManager.GetObject("quartzBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Acord_Uch, GreenLight
        ///      
        ///УрФУ, матмех
        ///2021.
        /// </summary>
        internal static string Signgature {
            get {
                return ResourceManager.GetString("Signgature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Slime {
            get {
                object obj = ResourceManager.GetObject("Slime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Spider {
            get {
                object obj = ResourceManager.GetObject("Spider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stoneBackground {
            get {
                object obj = ResourceManager.GetObject("stoneBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transparent {
            get {
                object obj = ResourceManager.GetObject("transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transparentDebug {
            get {
                object obj = ResourceManager.GetObject("transparentDebug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Позволь мне рассказать тебе вкратце как тут всё работает с:
        ///      
        ///Игра поделена на арены. На каждой твоя цель - победить всех монстров. Но ̶и̶з̶-̶з̶а̶ ̶к̶р̶и̶в̶о̶г̶о̶ ̶б̶а̶л̶а̶н̶с̶а это может быть не легко.
        ///Кхм, так вот. На каждое твоё действие тратятся твои ОД. Ты можешь их восстановить нажав на //Следующий ход//, но при этом совершат ход монстры.
        ///Так же тут ̶и̶з̶л̶и̶ш̶н̶е̶ ̶м̶у̶д̶р̶ё̶н̶а̶я не очевидная боевая система. Есть 3 основных показателя: Атака, Защита и Урон. Если кратко: чем больше а [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tutorial1 {
            get {
                return ResourceManager.GetString("Tutorial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты ещё читаешь это? Ну тогда лови более подробное объяснение системы расчёта урона:
        ///      
        ///1) Атака нападающего ≥ защиты обороняющегося:
        ///    a. Наносится полный урон;
        ///    b. Но если атака нападающего ≥ 1.25 * защита обороняющегося, то наносится на 50 % урона больше;
        ///      
        ///2) Атака нападающего &lt; защиты обороняющегося:
        ///    a. Наносится на 25 % урона меньше;
        ///    b. Но если атака нападающего ≤ 0.75 * защита защищающегося, то наносится на 50 % урона меньше.
        ///      
        ///Ах да, тут ещё есть консоль разработч [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tutorial2 {
            get {
                return ResourceManager.GetString("Tutorial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall0 {
            get {
                object obj = ResourceManager.GetObject("wall0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall1 {
            get {
                object obj = ResourceManager.GetObject("wall1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall2 {
            get {
                object obj = ResourceManager.GetObject("wall2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall3 {
            get {
                object obj = ResourceManager.GetObject("wall3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall4 {
            get {
                object obj = ResourceManager.GetObject("wall4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Witch {
            get {
                object obj = ResourceManager.GetObject("Witch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
